namespace LeagueOfLegendsFriendTournament.API.Helpers
{
    public enum GameTypeEnum
    {
        MOST_KILLS, MOST_WINS, MOST_DEATHS, LEAST_DEATHS, MOST_ASSISTS, LONGEST_LIVING_SPREE, LARGEST_KILLING_SPREE,
        MOST_GOLD_EARNED, MOST_TOTAL_DAMAGE_DEALT, LARGEST_VISION_SCORE, BEST_KDA_CHAMP_SPECIFIC, BEST_KDA_ROLE_SPECIFIC
    }
}